######################################################################
# Automatically generated by qmake (3.1) Thu Jan 25 22:42:51 2018
######################################################################

TEMPLATE = app
TARGET = meat
INCLUDEPATH += .

# Input
HEADERS += Box.h Dialog.h Mapping.h SingleMotor.h
SOURCES += Box.cpp Dialog.cpp main.cpp Mapping.cpp SingleMotor.cpp
